### ISSUE TITLE
Hook up contact us form to Eric's account

### ISSUE THREAD

**Issue by ericwjr** [onweru/fun#35]

**Comment by onweru** [comment]
Will set up after domain intergration

**Comment by onweru** [comment]
On your repo edit index.js line 45 (url: '//formspree.io/onewesh@gmail.com',) replace my email with yours

Also edit contact.md line 115 (<form  action = 'https://formspree.io/onewesh@gmail.com') ... again replace my email with yours.

**Comment by onweru** [comment]
That is how you hook up the contact form with your account
